### ISSUE TITLE
Add Gimbalabs PPBL to Plutus page

### ISSUE THREAD

**Issue by rphair** [cardano-foundation/developer-portal#1002]
I just noticed this in [Catalyst Weekly #70](https://forum.cardano.org/t/catalyst-weekly-70-voltaire-musings-film-festival-winners-fund10-updates-workshops-more/115915) ... https://plutuspbl.io ... and then ran to add it to the [Plutus page](https://developers.cardano.org/docs/smart-contracts/plutus), as an alternative / supplement to the Plutus Pioneer Program, only to realise I had no idea how to position it relative to that alternative.

I believe it should be displayed with corresponding rank, so that people know there's an alternative or addition to PPP that offers something similar.  I stopped my pending edit when I realised that putting them both on the Plutus page would require at least a brief explanation of _how they are **different**_.

Once clarified, I would be happy eiether to formulate this PR or to leave it to one of the contributors to https://github.com/cardano-foundation/developer-portal/pull/910 which had some good comments on the same subject by @OlofBlomqvist @rdlrt.

Maybe also we can ping someone at Gimbalabs to see how this could be introduced (the Catalyst text above seems a little too informal): @katomm @fill-the-fill, know of anybody?

**Comment by katomm** [comment]
Ok, summoning @rcmorano since I can't think of any other related GitHub account, but we could also send classy email. 😏

**Comment by rdlrt** [comment]
> I believe it should be displayed with corresponding rank

Not sure if I fully understood, but it could be mentioned briefly as an alternative learning module from gimbalabs (under [Getting Started with Haskell](https://developers.cardano.org/docs/smart-contracts/plutus/#get-started-with-haskell) , followed by a seperate section with short description before Demeter run (thus, education modules followed by sample simulation env)?

**Comment by rphair** [comment]
@rdlrt by "rank" I meant that I think it should have its own section: so yes, a section as you say, and because it's an educational programme it would be after PPP and therefore yes exactly before Demeter.run. 🤓

**Comment by OlofBlomqvist** [comment]
In my opinion, PPBL is a bit more beginner-friendly, but it also covers a broader scope of topics, including Plu-TS, PlutusTX, Aiken, Mesh, Koios, Demeter.run etc. I'd say it provides a more general introduction to the smart contracts landscape, so it might be better suited for the smart-contract overview page rather than the Plutus-specific page. This way, perhaps people who are interested in learning about Aiken or other non-plutus (read non-haskell-based) languages are more likely to notice it?

Regardless, it would ofc be polite to allow the Gimbalab team to describe their own project :) Maybe @jamesdunseith @workshop-maybe has some input?

**Comment by rphair** [comment]
@OlofBlomqvist I'd be happy to wait for a chance to @jamesdunseith @workshop-maybe to contribute, and if so will write up a PR with any text they provide, especially if it includes what you mention above.

**Comment by workshop-maybe** [comment]
Hi all - thanks for this thread, just catching it now! 

We are framing PPBL as a complement to PPP, not as an alternative, and students have reported benefits to doing both in parallel or in sequence. @OlofBlomqvist has it right above - PPBL is beginner friendly and introduces core concepts in Cardano development, not limited to Plutus. The full list of topics covered is at: https://plutuspbl.io/get-started/modules

Can it work to emphasize the complementary roles of PPP + PPBL? I can draft a blurb tomorrow if needed.

(And thanks for tracking me down - Gimbalabs doesn't have too much of a github presence because we gitlab as a reminder that there are always alternatives in the decentralized world we're buliding)

**Comment by rphair** [comment]
@workshop-maybe - a blurb with everything you just mentioned sounds perfect & such a positioning of PPBL relative to PPP is exactly what I was hoping for in posting this issue 🤓

**Comment by rphair** [comment]
@workshop-maybe - a blurb with everything you just mentioned sounds perfect & such a positioning of PPBL relative to PPP is exactly what I was hoping for in posting this issue 🤓

**p.s.** if you post some markdown here I'll put it into a PR for that page, or if you don't mind engaging with our centralised GitHub you can post the PR yourself 😎

**Comment by workshop-maybe** [comment]
Thank you @rphair - just submitted a PR. Feel free to change anything I wrote as you see fit -- and thanks for the opportunity to share!

**Comment by rphair** [comment]
and thank _you_ @workshop-maybe ... looks all in order so any further editing can continue in the PR.
