### ISSUE TITLE
Update links to GitHub repos moved to IntersectMBO

### ISSUE THREAD

**Issue by override-applied** [cardano-foundation/developer-portal#1182]
The Cardano-node repositories have migrated to Intersect MBO, but the tutorial on developers.cardano.org is lagging this info. Following the documentation in the tutorial leads to errors.

**Comment by rphair** [comment]
ugh, thanks @override-applied, we are in the process of realising this.  It affects multiple pages beyond the one you reported; I can submit a PR to find-replace them but @rdlrt @Ryun1 do either of you have a complete list of the ones that have officially moved, rather than having to trust my empirical observations?  cc @katomm

**Comment by Ryun1** [comment]
I think the list would just be all the repositories under the IntersectMBO github org:
https://github.com/orgs/IntersectMBO/repositories

**Comment by rphair** [comment]
That list would be useful if it could be narrowed down to all items that have been migrated from https://github.com/input-output-hk (or maybe in some cases https://github.com/cardano-foundation ?)...

**Comment by Ryun1** [comment]
The only repositories which was present in Intersect org before the migration were [community](https://github.com/IntersectMBO/community) and [cardano-test-plans](https://github.com/IntersectMBO/cardano-test-plans). The rest I believe all came from IOHK 🤓.

**Comment by rphair** [comment]
Fixed by https://github.com/cardano-foundation/developer-portal/pull/1260.
