### ISSUE TITLE
404 on cardano-cli link

### ISSUE THREAD

**Issue by bezirg** [cardano-foundation/developer-portal#1327]
The link should be updated from

https://github.com/IntersectMBO/cardano-node/tree/master/cardano-cli#cardano-cli   (404 now)

to

https://github.com/IntersectMBO/cardano-cli

![image](https://github.com/user-attachments/assets/ffb12d30-657c-4a95-93db-978f6c000221)

**Comment by rphair** [comment]
@katomm @CarlosLopezDeLara I think this is important to justify its own PR to fix it, rather than waiting to search for similar problems.

@bezirg this will be fixed by https://github.com/cardano-foundation/developer-portal/pull/1329 as soon as it's merged into `staging` and then migrated to the production branch soon after.
