### ISSUE TITLE
SPO course, security review needed 

### ISSUE THREAD

**Issue by katomm** [cardano-foundation/developer-portal#42]
The content currently in the stake pool course needs a security review on best practices when it comes to key-related things.

We should not write content like "in the testnet, you can do it like this" - no, stake pool operators should learn how to do things the right away from the beginning.

Please also see this related issue: https://github.com/cardano-foundation/developer-portal/issues/43

**Comment by rphair** [comment]
In trying to answer https://github.com/cardano-foundation/developer-portal/issues/43 I had to do a complete security review.  After a few days I have the results outlined & will get to work now on modifying the doc pages, and post it as a PR ASAP in the next few days.  Here are the main changes:

---------------

first, a new Air Gap Environment page in the Get Started section (not the SPO Course, since it's also needed for Devs to work with *their* keys).  As necessary, particular notes about working with keys & data will point back to this document.

interjections into several each of the Dev and SPO pages highlighting how to keep & work with the keys, rather than keeping them (as per the testnet oriented instructions) by default assumption on a node or Internet connected machine.

create another page (before Builder Tools, "Using keys on application servers") with some general cautions about keeping payment keys on live servers if & when necessary to use those particular tools, which have wallet passphrases & private keys in the cleartext code in several places through this section of the Dev Portal.

... This page would probably be just a stub for now because the problem of key management on servers doing automatic transaction process is more general & complicated than the problem of user key management which needs to be addressed first.  Some application oriented devs can help fill out this page later (?).

the "Integrate Cardano" section is now written as a series of testnet tutorials, so to avoid ripping all that documentation apart I would add a final "Working on the Mainnet" page in that section of mainnet equivalents if they exist (not for everything: there's no "faucet", you can't give yourself funds so no point creating an extra CLI wallet, etc.)

... to avoid duplication of effort the Mainnet page will insist that the reader complete the Testnet tutorials and then return here for an explanation of how to do these things in production.

... since "Build with transaction metadata" and "Discover Native Tokens" are also introduced with testnet commands, each of these sections will need to be concluded with their own "Working on the Mainnet" page.

The Stake Pool Course (particularly the SPO Handbook; the Lessons are all video) needs the same treatment but has some missing & redundant sections as well:

... The KES key instructions are incorrect (only appropriate to testnet) as well as insecure (missing any standard for working with these or any other private keys) and in the wrong place (instead of before generating the op cert, they're in an appendix of "Assignments" for the testnet).

... Obviously the "KES periods" information for testnet is all wrong & instructions need to be updated for mainnet.  I believe there's no point keeping a "KES testnet" page around (even if it didn't cause confusion) because the rest of the instructions for creating a pool on testnet are on video, **not** text pages.

... this is fixed by moving KES / VRF key instructions into the latter of 2 duplicate pages ( "Create stake pool keys" / "Creating keys and address") and making sure that page is before the instructions for KES periods & op certs.

Then there needs to be one more page ("Key Security") in the SPO Handbook, immediately before the page "Creating keys and addresses which lists all the keys mentioned later (in "Register a Stake Pool with Metadata"), indicating which keys should never leave the Air Gap, and which ones will need to be carefully installed on the block producer.

Finally the Air Gap semantics for the rest of the SPO Handbook pages should not be too hard to add, because it will apply the same transaction semantics over & over again (gather information on your node, build transaction in air gap, copy signed Tx back to your node).

--------------

This is the minimum modification that I think will do it.  It will at least update the incorrect information in the documentation so it won't be necessary for all readers to look for other resources beyond the Dev Portal to complete their stake pool.  I'll get that PR posted ASAP, but even after discussion continues there please feel free to use this as a checklist.

**Comment by rphair** [comment]
> We should not write content like "in the testnet, you can do it like this"

@katomm while the SPO section itself is being reorganised please let me know what you think of the 2 proposed pages in https://github.com/cardano-foundation/developer-portal/pull/665 (the testnet transaction model updated for a secure workflow on mainnet nodes + an air gap building procedure).

**Comment by katomm** [comment]
I think that is very good and I am glad that someone is stepping up to address this. I would love  to see you as a reviewer in the developer portal in case you are interested @rphair

**Comment by rphair** [comment]
sure, I'm interested ... feel free to PM me in Discord  😎

**Comment by katomm** [comment]
Awesome. Invite sent, I also wrote you on Discord.
