### ISSUE TITLE
SPO course, security chapter missing

### ISSUE THREAD

**Issue by katomm** [cardano-foundation/developer-portal#43]
The stake pool course needs a security chapter (better the topic should run through the whole course, but you have to start somewhere). We can use this issue to discuss ideas, requirements or any thoughts.

If anyone found their way here because they thought they were getting safety tips for their stake pool, please read on here: https://forum.cardano.org/c/staking-delegation/stake-pool-security/157

The security chapter should make clear that you must not have any payment key on the server. Also: how to handle keys in a secure way.

It would also be interesting to mention what people can do if there is more than one operator. Maybe one wants to share the stake key.
How to create, handle and sign transactions on an air-gapped machine.
Probably interesting also the scripts and how-tos that Martin did: https://forum.cardano.org/t/new-ledger-trezor-update-for-owner-pledge-stakepool-operator-scripts/43953

In general, the https://forum.cardano.org/c/staking-delegation/stake-pool-security/157 is full of great posts around this topic and I'm sure other people have even better ideas what to put in.

Please also see this related issue: https://github.com/cardano-foundation/developer-portal/issues/42

**Comment by rphair** [comment]
@katomm we've prepared building instructions for an air gapped environment ([here](https://cosd.com/frankenwallet), posted on IO's Essential Cardano list under [Other Community Resources](https://github.com/input-output-hk/essential-cardano/blob/main/essential-cardano-list.md#other-community-resources)).  This would provide some foundation for a security topic, but where in the current Developer Portal outline would we contribute it?

1. Given that this documentation is already available externally, would it be enough to link to it, or must it be duplicated in a Developer Portal page?
2. Also, since an air gapped host is always useful to Operate a Stake Pool but also to Minting Native Assets, how would this reference best be posted so it's accessible to these two separate categories?

I know the security topic is broad, highly debatable, and full of liability issues.  The material I've written introduces some of the most critical security concepts so that the operator / developer can make their own decisions about them, and offers some practical guidelines.  To avoid over-committing to specific procedures, it could therefore be preferable to keep it as an external link (with the appropriate disclaimer) rather than reposting the material here.

These instructions were written mainly for building an air gap environment on a memory stick but the procedures & security concepts will also be applicable when installing a conventional air gap machine.

@rdlrt I can see that you made a similar comment here (https://github.com/cardano-foundation/developer-portal/pull/331#issuecomment-927455807) although I'd still be unsure how to integrate material on "air gapping" given that no two SPOs or developers will completely agree on exactly how an "air gap" host should be built.

**Comment by rphair** [comment]
p.s. I've just found a heading in the Operate a Stake Pool section where it would be appropriate to add an external link: https://developers.cardano.org/docs/operate-a-stake-pool/#stake-pool-operator-resources
... but I haven't found anything equivalent in Minting Native Assets with standards or tools for working securely with private keys.

**Comment by rphair** [comment]
> The stake pool course needs a security chapter (better the topic should run through the whole course, but you have to start somewhere)

@katomm as per my last comment in https://github.com/cardano-foundation/developer-portal/issues/42 I've now gone through every page on the Dev Portal and the only chapter completely missing is a guide to *Create an Air Gap Environment* to work with keys securely.

Other security audited pages can then be updated to insist that the user building a stake pool on mainnet will have to do certain things (key generation & signing) on that Air Gap environment.

Since the Air Gap is not just for SPOs (it's also needed for transactions of token minting & NFT production, etc.) this page has to be early in the Dev Portal before the "builder" material... i.e. in the Get Started section, between Cardano Components and Builder Tools (which often also rely on key files which should be securely generated).

This Air Gap page might be a single page or a series of pages.  I'd prefer to post a single long page for now & perhaps break up later as part of another PR, since it will be coming in through a big PR with lots of other security related edits.

The stake pool course will then be able to refer to the Air Gap and insist that it be used for secure transactions & keeping all the SPO's keys.

Until there's a PR I have a list of other changes in progress in https://github.com/cardano-foundation/developer-portal/issues/42 ... everything in this OP should be addressed  except:

> It would also be interesting to mention what people can do if there is more than one operator. Maybe one wants to share the stake key.

... I'll save that one for later because: this security "audit" omnibus PR is already going to be huge, and it will be easier for someone to add this later on top of the *basic* key management principles because it represents a different kind of security issue than simply working safely with one's own development & SPO keys.
