### ISSUE TITLE
SPO Sidebar navigation

### ISSUE THREAD

**Issue by sanskys** [cardano-foundation/developer-portal#641]
I am updating the SPO part and will do it in several small steps. The first topic is:
-  to reorganize the Stake Pool section and integrate the content in the handbook into the course. The new sections could be 
1) Introduction 
2) Pre-requisites 
3) Installing & Configuring Cardano Nodes 
4) Registering a Pool 
5) Pool Maintenance 
6) Tools and Links

![SPO Sidebar](https://user-images.githubusercontent.com/80989645/170722739-45ef9d81-cc8d-4892-ab16-d188853f98c0.JPG)

**Comment by katomm** [comment]
I think getting rid of the lesson titles and merging the "handbook" with the course is a great start. What we need to keep in mind is to set proper redirects for sites that no longer exist.  

This can be done in docusaurus.config.js below "redirects".

**Comment by rdlrt** [comment]
Just a small point here, prolly good to avoid duplication (installing cardano node is already a section [here](https://developers.cardano.org/docs/get-started/installing-cardano-node) and could be referenced)

**Comment by rphair** [comment]
Looking at SPO & developer security as an urgent, bare minimum update to the existing pages, I recently did a security review of the current material in the SPO & other sections: https://github.com/cardano-foundation/developer-portal/issues/42#issuecomment-1157180181 ... but I wouldn't be able to submit the changes I've started working on because they would no longer apply to this proposed page reorganisation.

Most of my work is related to key management which is also a topic here, so many of these changes might already be covered by someone else's pending work (?): https://github.com/cardano-foundation/developer-portal/issues/641#issuecomment-1147505973

@katomm @rdlrt what is the overall plan for coordinating & scheduling these changes?  I can still apply my audit results to a new set of pages (most of my security recommendations are already published [here](https://cosd.com/frankenwallet/prepare)) so rather than try to push it out this weekend I would prefer to wait for a sensible page reorganisation before adding the security related material.

In the meantime since building an Air Gap environment is necessary in general for key management (_by devs as well as_ SPOs) I'm going to work on that topic: https://github.com/cardano-foundation/developer-portal/issues/43#issuecomment-1157181551) ... this would be be pushed as its own page or set of pages in the Get Started section, so would be separate from the SPO menu structure.

Meanwhile I can wait for @sanskys @VitoMelchionna to finish this reorganisation before submitting any wide-reaching security update.  I'd also be happy to coordinate in the writing of some of the pages above & will watch here for a response about that. 😎

**Comment by rdlrt** [comment]
> what is the overall plan for coordinating & scheduling these changes? I can still apply my audit results the new system of pages (most of my security recommendations are already published [here](https://cosd.com/frankenwallet/prepare)) so rather than try to push it out this weekend

Afaik - atm, we haven't pushed for timings to follow as it would depend on free time from those who have shown interest to complete the re-org.

Meanwhile - personally - I believe the security (Key management as well as for Node Operation) section could be included as a seperate page (eg : `Security Best Practices`) under Stake Pool Course (which can be linked from other pages as part of recommendations). You can either wait for #658 to be updated/merged, or use that branch as base to add security-best-practices page.

@sanskys - Pardon my ignorance earlier with approval, I might have rushed into approval before😢 found few tiny bits to update in #658 , as part of which I've also asked to add a placeholder page (content could be To-Do) to the `sidebar.js`

**Comment by rphair** [comment]
> You can either wait for https://github.com/cardano-foundation/developer-portal/pull/658 to be updated/merged, or use that branch as base to add security-best-practices page.

thanks @rdlrt - I definitely hadn't thought of that.  I'll use that branch for the new pages (Air Gap & Security Best Practices page) and stay tuned here about the rest.

**Comment by rphair** [comment]
FYI the last cross reference was about whether to use `transaction build-raw` vs. `transaction build` and to perhaps address how to use the ledger era option (e.g. `--alonzo-era`) when creating transactions.

**Comment by sanskys** [comment]
integrated into #737
