### ISSUE TITLE
How to deal with NFT showcase

### ISSUE THREAD

**Issue by katomm** [cardano-foundation/developer-portal#818]
For more than a year, we have been discussing here on the developer portal how best to handle NFT/ tokens in the showcase. But, since the GitHub discussions do not have quite as much visibility as the issues I would like to link to it again:  [NFT Showcase Discussion](https://github.com/cardano-foundation/developer-portal/discussions/243) at the same time asking for thoughts and participation in general.

**Comment by rphair** [comment]
To restate how I feel from [this thread](https://github.com/cardano-foundation/developer-portal/discussions/243#discussioncomment-3828268) (and then I'll stand aside to hear opinions that haven't been presented yet):

1. I agree with @katomm about listing the 10+ most popular projects as per OpenCNFT.
2. I think we can also add tokens with _utility_, i.e. integrated into some kind of economy which is documented and demonstrably working. 

There will be some overlap between categories 1 and 2, though probably not many in category 2 that aren't in category 1 because ground breaking NFT projects at this stage would tend to attract a lot of commercial interest... but not always, and I think we want to give some smaller devs a chance if they're advancing the Cardano ecosystem & community in a unique way, right? 🤓

**Comment by katomm** [comment]
NFT update proposal that considered everything that was discussed: https://github.com/cardano-foundation/developer-portal/pull/1012
