### ISSUE TITLE
Cannot see any items in the showcase section of the site

### ISSUE THREAD

**Issue by GGAlanSmithee** [cardano-foundation/developer-portal#827]
Sorry if this is known or excpected, but navigating to the [showcase page](https://developers.cardano.org/showcase/?tags=nft) there simply aren't anything showing there. There are other issues related to showcase, like https://github.com/cardano-foundation/developer-portal/issues/818 which seem to allude to that there should be items there.

Win 10, latest Brave.

**Comment by rphair** [comment]
The link you are using above:
> https://developers.cardano.org/showcase/?tags=nft

is using the `nft` tag, which is defined for the Builder Tools section but undefined for the Showcase section.  It's returning an empty set because there is no such tag... as it would for any nonexistent tag, e.g.: https://developers.cardano.org/showcase/?tags=sillyUndefinedTag

FYI... NFT-centred projects in the Showcase are defined by two separate tags:

- https://developers.cardano.org/showcase/?tags=nftproject
- https://developers.cardano.org/showcase/?tags=nftsupport

**Comment by GGAlanSmithee** [comment]
@rphair 

In that case, you have a broken link [here](https://developers.cardano.org/docs/native-tokens/)

![image](https://user-images.githubusercontent.com/11805103/195896955-5856b039-b81d-4a3f-97ed-945dd8bef5bc.png)

**Comment by GGAlanSmithee** [comment]
From the "Getting Started" -> "Discover Native Tokens" page

**Comment by rphair** [comment]
Thanks for the further detail @GGAlanSmithee ... we can leave this open until the correction in #828 is merged into the `staging` branch (which means it will be published to the web site at the next interval). 🤓

**Comment by GGAlanSmithee** [comment]
Cheers!

**Comment by katomm** [comment]
nice catch!
