### ISSUE TITLE
Document how to get Faucet API key

### ISSUE THREAD

**Issue by mgajda** [cardano-foundation/developer-portal#837]
As community of Cardano Developers grows, the need for testnet Ada may increase.

There is a faucet here: https://docs.cardano.org/cardano-testnet/tools/faucet
Unfortunately the process of issuing API keys is undocumented.

Would it be possible to add a direct link where to apply?
Possibly a form to fill in?

**Comment by rphair** [comment]
@mgajda yes it is definitely possible to add such a link & we could do this immediately, but I don't have that information & don't know who does.  There are a couple threads on this subject on the Cardano Forum which ask this question, but none provide an answer: going back over a year & remaining unanswered for the new testnets.

copying some people across the board who may know: @katomm @rdlrt @fill-the-fill @oversize @KtorZ

**Comment by oversize** [comment]
Hey, 

unfortunately i don't know. I was in the same situation a few weeks ago (asking myself where would i get such a key). @mgajda are you needing the api key for a specific reason or just asking out of curiosity? You can get a bunch of ada once a day and the key would only allow you to request more than once a day not to receive more ada.I do agree though that if there is the option to provide a key, it should be also mentioned how/where to get one.

However, i think that having the faucet be available to get drained huge amounts of ada from by basically everyone all the time, might put the network in a struggle where more and more ada is locked in dev/test keys that are either lost or otherwise non accessible anymore. But that is a discussion that should be held by the people operating the testnet which currently is IOHK.

**Comment by rdlrt** [comment]
The API key is currently part of pinned message in IO testnet channel on discord and telegram. It is meant to be used only by participants of those networks, but agree that it's not obvious where to locate the groups.

As regards the actual funds, if the intention is to test creation of blocks - you have delegation option wherein upon requesting from faucet, a new account will be provisioned and provide you 1M delegation against your pool registered. Thus, there shouldn't really be a need to abuse faucets (has happened a lot in the past networks) unless doing tx spam tests and so on

**Comment by rphair** [comment]
My reading of the discussion so far is:

- We _could_ copy the API instructions from the "IO testnet channel" on Discord or Telegram into the testnet page here on the Dev Portal.
- We _should_ probably _not_, because that's not the way the faucet distribution was designed to work in the general case.

@mgajda are you satisfied with knowing the answer, enough for this to be closed?  I understand a case could be made to publicise a deeper level of the faucet API, but I believe it would encourage pathological behaviour like hoarding testnet tokens & therefore that things should be left the way they are.
