### ISSUE TITLE
Can not download cardano-node binaries anymore

### ISSUE THREAD

**Issue by pgrange** [cardano-foundation/developer-portal#871]
Hello,

The links to download the cardano-node binaries do not work anymore on the [installing cardano-node](https://developers.cardano.org/docs/get-started/installing-cardano-node) page.

<img width="965" alt="Capture d’écran 2022-12-02 à 13 48 39" src="https://user-images.githubusercontent.com/378506/205296505-d23b5a33-d590-4d03-8109-c2abefb6ab9f.png">

As a matter of fact https://hydra.iohk.io seems to be down :(

It's a shame as it was super useful to get the binaries straight from there for installing. Do you know if they've been moved or something?

**Comment by pgrange** [comment]
FYI, I found them here: https://github.com/input-output-hk/cardano-node/releases

**Comment by pgrange** [comment]
FYI, I've managed to find the links in the release notes of cardano-node but they are broken too: https://github.com/input-output-hk/cardano-node/issues/4688

**Comment by ch1bo** [comment]
You can use cache.iog.io as a drop in replacement. IMPORTANT: keep the public key with the hydra.iohk.io prefix, it's still used AFAIK

**Comment by rphair** [comment]
@katomm @fill-the-fill @oversize who do we contact about an upstream (IOG server) problem like this?

**Comment by rdlrt** [comment]
The hydra links will not defunct, hyperlinks in cardano-node release notes have been updated accordingly

**Comment by rphair** [comment]
@katomm I would feel horrible about updating all references to the precompiled binary package on the Developer Portal every single time a new `cardano-node` was released... even now I wouldn't be sure I could find all of them.  I'll update the current link now, but perhaps you could lend some weight to my request at https://github.com/input-output-hk/cardano-node/issues/4688#issuecomment-1336154065 for a standard URI that will always point to the latest current binary package.

My guess is they would be able to do this because https://update-cardano-mainnet.iohk.io looks like a programmatic web site which is already generating RDF listings.

**Comment by rphair** [comment]
thanks @rdlrt - I'll follow that other issue as well and we'll see what happens. With a little help from the IOG end, something could parse the RDF at https://update-cardano-mainnet.iohk.io to get the latest download link... failing that, it could be scraped out of the HTML on the GitHub Release page 😰

Anyway have posted https://github.com/cardano-foundation/developer-portal/pull/873 to fix the content in the short term.
