### ISSUE TITLE
Issue with building cardano-node: Fedora 37 official repos do not contain ncurses-compat-libs

### ISSUE THREAD

**Issue by LukaKurnjek** [cardano-foundation/developer-portal#886]
I followed the procedure https://github.com/cardano-foundation/developer-portal/blob/staging/docs/get-started/installing-cardano-node.md on my Fedora 37 (newest version as of writing) and found out that the package ncurses-compat-libs that is needed to install the cardano-node is not contained anymore in official Fedora repositories. Tried to install the Fedora 36 version of this package on Fedora 37 and had dependency issues. Not sure whether the same problem also appears for the newest RHEL.

**Comment by rdlrt** [comment]
Can this be raised against [cardano-node](https://github.com/input-output-hk/cardano-node) repo? ncurses-compat-libs was dropped in RHEL/Fedora from ncurses-6.3.1 as the newer ABI has been live since 7 years. There are hacks around (installing ncurses and creating symlink /usr/lib64/libncurses.so.5 pointing to /usr/lib64/libncurses.so.6), but should be easier to solve correctly
