### ISSUE TITLE
moderation oversight requested on Cold Fusion cardano-wallet builder tool

### ISSUE THREAD

**Issue by fangio10** [cardano-foundation/developer-portal#895]
So I've built a cardano wallet API wrapper in ColdFusion to simplify integration of cardano payments and other wallet functions on ColdFusion based apps.

Please advise if such a tool has no place on the cardano devs website,  pull request details:
https://github.com/cardano-foundation/developer-portal/pull/894

This builder tool is comparable to various others that are featured.

**Comment by rphair** [comment]
I was trying to explain (maybe too briefly) in https://github.com/cardano-foundation/developer-portal/pull/894#pullrequestreview-1225669127 that I didn't think this PR was prematurely closed by @rdlrt - due to effectively (and perhaps subtly) being "off topic" for the repository itself.

Personally (as I think is also true for most of the collaborators on this repository who actively edit pages & projects) _I get an individual email for every single comment, review, commit, and PR submission / open / close on the repo_.  Therefore it's not possible for any editor to make a unilateral decision and close off an issue or PR before it's gotten the attention of the entire team... e.g. this is why I noticed this issue immediately after your PR (sorting email by subject in a daily review of this repo activity).

I understand you could have felt that you were treated more diplomatically if the PR had been left open long enough to get a number of symmetrically provided rejections... but in reality our process doesn't work that way.  Most editors will only produce an approving review, and if not ready to accept a project will just leave a PR alone until someone decides to endorse it... until it finally gets closed in some administrative sweep after an indeterminate time.

This process isn't perfect, but I believe it's why @rdlrt stepped up and asserted that the project wasn't suitable for the Dev Portal... in a way other editors would understand & agree with... rather than letting it linger around with uncertainty for you & editors alike.  In any case I hope a better understanding about how our (mostly volunteer) editors work together will help you understand that there is neither a lack of moderation here nor any "unfair" treatment in your case. 🙏

cc: @katomm @fill-the-fill @os11k (the most frequent editors on the collaboration list, according to my memory)

**Comment by katomm** [comment]
I second what @rdlrt and @rphair wrote. Suggestion: you can try and add your project to https://github.com/input-output-hk/essential-cardano

**Comment by fangio10** [comment]
> I second what @rdlrt and @rphair wrote. Suggestion: you can try and add your project to https://github.com/input-output-hk/essential-cardano

thank you, i was under the impression that the developer portal was a place were we could share open source solutions for those interested in working with or integrating cardano - clearly I was wrong about that.

thanks for pointing out essential-cardano
