### ISSUE TITLE
ISPO Marketplace - Would this be a good addition to the Showcase section?

### ISSUE THREAD

**Issue by thenic95** [cardano-foundation/developer-portal#920]
Hello everyone,

At the beginning of this week, I stumbled upon this [website](https://www.gomaestro.org/marketplace) that aggregates currently available ISPOs on Cardano. It's a very useful site and I would love to hear your opinion about adding this to the showcase section.

Thanks & Have a great day,
Nicolas

**Comment by rphair** [comment]
thanks @thenic95 for pointing that out.  I'd feel reluctant to include it because then it might compel us to include other ecosystem features which have primarily an "investment" or "financial" purpose, rather than supporting the underlying technology as I believe the Developer Portal is mandated to do.

Also, the last year's standards-oriented discussions of RSS (Rewards Sharing Schemes) have confirmed what I always felt as a stake pool operator: that ISPO's have a catastrophic effect on the design principles of Cardano's PoS system... whether your goal is a stable and secure centralisation or a "fair" decentralisation in which smaller operators can compete.

So it may not be a "healthy" thing to include but I wouldn't insist upon keeping it out.  Mainly I'm worried that our developer & technological views of the ecosystem could be contaminated by the same money & marketing rubbish that we have all over other blockchains.  I would go along with the consensus if it suggests otherwise... and then steel myself for an onslaught of navigators for other Cardano money-based propositions, in whatever Showcase category the "ISPO Marketplace" was assigned to. 😖

**Comment by thenic95** [comment]
Hi @rphair, thank you for getting back to me. I had very similar feelings and thoughts about this. 

As you said, ISPOs are an interesting concept by themselves, and as far as I'm aware, their impact or existence has not been considered in Cardano's game theory. I think it's very interesting how many ada holders give up their "normal" delegation rewards for some promises of a future token with questionable utility, but that's a different discussion 😄

**Comment by rphair** [comment]
> how many ada holders give up their "normal" delegation rewards for some promises of a future token

Interesting case in point: this posting, which retracts that original premise and restores what the native ada rewards would have been, as if the promised token had no additional intrinsic value (something generally _not_ assumed during the initial "bonanza" days of ISPOs): https://medium.com/@axotrade/axo-airdrop-a47594f1696b

**Comment by rphair** [comment]
Another question is whether or not ISPO explorers would ever be able to establish enough context for users to judge offerings comparatively: with one apparently pathological case brought up for discussion in the community today: https://forum.cardano.org/t/there-is-an-urgent-need-for-business-mentorship/112745

**Comment by rdlrt** [comment]
In my (sorry if too loud and non-diplomatic) view, ISPOs primarily is just a way to gain financial assistance than anything else - at the expense of manipulating research's assumptions of how a delegator would behave, it does not have anything remotely related to content for developer portal (neither for education, nor for innovation/use-case) - similar to ICO/IPO , listing them can only deteriorate levels as (like essentials) having a mention on a domain ending with cardano.org is often projected as 'partnered with' by a % of projects as part of their promotions.

**Comment by thenic95** [comment]
I agree @rdlrt 

Thank you for both of your comments. I'll close the issue for now :)
